import { DocLayout, PageHeader } from '@/components/layout/DocLayout'
import { CodeBlock } from '@/components/docs/CodeBlock'
import { ApiSection, Callout } from '@/components/docs/ApiSection'
import { useLang } from '@/context/LangContext'

const TUNNEL_CMD = `# Start with ngrok tunnel
egm simulate --tunnel

# Output:
# EGM Simulator   v0.1.0
# Project         My Game
# ─────────────────────────────────
# Local    http://localhost:5173
# Tunnel   https://abc123.ngrok.app  ← scan this QR with EgmGO`

const EGMGO_MANIFEST = `<!-- public/__go.html — auto-generated by EGM -->
<!-- Scan this URL with the EgmGO app to connect -->
{
  "name": "My Game",
  "version": "0.1.0",
  "gameUrl": "https://abc123.ngrok.app",
  "width": 800,
  "height": 600
}`

export function SimulatorPage() {
  const { lang } = useLang()

  return (
    <DocLayout>
      <PageHeader
        title={lang === 'en' ? 'Simulator' : 'Simulador'}
        badge="CLI"
        description={
          lang === 'en'
            ? 'The EGM simulator wraps your game in a device frame with DevTools, live reload, console capture, and remote testing via ngrok.'
            : 'O simulador EGM envolve seu jogo em um frame de dispositivo com DevTools, live reload, captura de console e testes remotos via ngrok.'
        }
      />

      <div className="space-y-10">
        <ApiSection title={lang === 'en' ? 'Starting the simulator' : 'Iniciando o simulador'}>
          <CodeBlock code="egm simulate" lang="bash" />
          <p className="text-[#8888aa] text-sm mt-3 leading-relaxed">
            {lang === 'en'
              ? 'The simulator starts a Vite dev server and opens a browser page at http://localhost:5173 with a device frame (phone, tablet, or desktop), DevTools panel, and live-reload support.'
              : 'O simulador inicia um servidor Vite e abre uma página no browser em http://localhost:5173 com um frame de dispositivo (celular, tablet ou desktop), painel DevTools e suporte a live-reload.'}
          </p>
        </ApiSection>

        <ApiSection title={lang === 'en' ? 'DevTools overlay' : 'Overlay DevTools'}>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {[
              { icon: '📊', en: 'Inspector', pt: 'Inspector', desc_en: 'Live display tree with transform values', desc_pt: 'Árvore de display com valores de transform em tempo real' },
              { icon: '⚡', en: 'Performance', pt: 'Performance', desc_en: 'FPS graph, draw calls, physics step ms', desc_pt: 'Gráfico FPS, draw calls, tempo da física' },
              { icon: '💬', en: 'Console', pt: 'Console', desc_en: 'Console capture from the game iframe', desc_pt: 'Captura de console do iframe do jogo' },
            ].map(t => (
              <div key={t.en} className="bg-[#111118] border border-[#1e1e2a] rounded-xl p-4">
                <span className="text-2xl">{t.icon}</span>
                <p className="text-[#f0f0f8] text-sm font-semibold mt-2">{lang === 'en' ? t.en : t.pt}</p>
                <p className="text-[#55556a] text-xs mt-1">{lang === 'en' ? t.desc_en : t.desc_pt}</p>
              </div>
            ))}
          </div>
        </ApiSection>

        <ApiSection title={lang === 'en' ? 'Device skins' : 'Skins de dispositivo'}>
          <p className="text-[#8888aa] text-sm leading-relaxed">
            {lang === 'en'
              ? 'Switch between device frames in the simulator toolbar: iPhone, Android, tablet, TV, or bare canvas. The game is embedded as an iframe with the selected skin applied around it.'
              : 'Troque entre frames de dispositivo na barra do simulador: iPhone, Android, tablet, TV ou canvas puro. O jogo é embutido como iframe com a skin selecionada aplicada ao redor.'}
          </p>
        </ApiSection>

        <ApiSection title={lang === 'en' ? 'ngrok tunnel — test on real devices' : 'Túnel ngrok — testar em dispositivos reais'}>
          <CodeBlock code={TUNNEL_CMD} lang="bash" />
          <Callout type="info">
            {lang === 'en'
              ? 'EGM auto-downloads the ngrok binary. No account required for basic usage. The tunnel URL is displayed in the terminal and as a QR code.'
              : 'O EGM baixa automaticamente o binário ngrok. Nenhuma conta necessária para uso básico. A URL do túnel é exibida no terminal e como QR code.'}
          </Callout>
        </ApiSection>

        <ApiSection title="EgmGO — __go.html">
          <p className="text-[#8888aa] text-sm leading-relaxed mb-4">
            {lang === 'en'
              ? 'When running with --tunnel, EGM generates a `public/__go.html` handshake file. The EgmGO native app (iOS/Android) reads this to open your game in an optimized WebView.'
              : 'Ao executar com --tunnel, o EGM gera um arquivo handshake `public/__go.html`. O app nativo EgmGO (iOS/Android) lê isso para abrir seu jogo em um WebView otimizado.'}
          </p>
          <CodeBlock code={EGMGO_MANIFEST} lang="json" filename="public/__go.html" />
        </ApiSection>
      </div>
    </DocLayout>
  )
}
