import { t, type DocPage } from '../../types'

const page: DocPage = {
  slug: '/3d/sound',
  title: t('sound', 'sound'),
  description: t(
    'Synthesised sound effects and a music bed generated with the Web Audio API, so there is never a file to load.',
    'Efeitos sonoros sintetizados e uma trilha de fundo gerados com a Web Audio API, então nunca há arquivo para carregar.',
  ),
  source: 'src/engine3d/sound.ts',
  related: ['/3d/engine', '/3d/input', '/3d/hud', '/3d/state'],
  sections: [
    {
      id: 'overview',
      title: t('Synthesised, never loaded', 'Sintetizado, nunca carregado'),
      blocks: [
        {
          type: 'p',
          text: t(
            '`createAudio({ volume })`, or `game.audio`. Every sound is generated by the Web Audio API (Application Programming Interface, interface de programação) at the moment it plays, so nothing can fail to load and there is nothing to fetch. Oscillators and filtered noise are exactly what arcade sound effects are. Audio unlocks itself on the player\'s first click, tap or key (a browser rule, and the usual reason a game "has no sound"), so a game never has to think about it.',
            '`createAudio({ volume })`, ou `game.audio`. Todo som é gerado pela Web Audio API (Application Programming Interface, interface de programação) no instante em que toca, então nada falha ao carregar e não há nada para baixar. Osciladores e ruído filtrado são exatamente o que são os efeitos sonoros de arcade. O áudio se destrava sozinho no primeiro clique, toque ou tecla do jogador (regra do navegador e o motivo usual de um jogo "ficar sem som"), então o jogo nunca precisa pensar nisso.',
          ),
        },
        {
          type: 'code',
          lang: 'ts',
          title: t('Built-in, custom and music', 'Embutidos, próprios e música'),
          code: `import { createGame } from 'easy-game-maker/3d'

const game = createGame()

game.audio.define('zap', () =>
  game.audio.tone({ frequency: 1200, type: 'sawtooth', slide: -900, duration: 0.12 }),
)

window.addEventListener('pointerdown', () => {
  game.audio.play('coin', { vary: 0.1 })
  game.audio.play('zap', { pitch: 1.2 })
})

game.audio.music.start({ notes: [220, 277, 330], tempo: 180 })`,
        },
      ],
    },
    {
      id: 'play',
      title: t('Playing sounds', 'Tocando sons'),
      blocks: [
        {
          type: 'table',
          head: [t('Name', 'Nome'), t('Signature', 'Assinatura'), t('Notes', 'Notas')],
          rows: [
            [t('`createAudio`', '`createAudio`'), t('`createAudio({ volume = 0.35 }) => GameAudio`', '`createAudio({ volume = 0.35 }) => GameAudio`'), t('Master volume 0 to 1.', 'Volume mestre de 0 a 1.')],
            [t('`audio.play`', '`audio.play`'), t('`play(name, { pitch = 1, vary = 0 })`', '`play(name, { pitch = 1, vary = 0 })`'), t('`pitch` multiplies every note; `vary` is random pitch wander as a fraction (`0.1` is +/-10%). Use `{ vary: 0.1 }` on anything that fires repeatedly. Does nothing for an undefined name.', '`pitch` multiplica cada nota; `vary` é a variação aleatória de tom em fração (`0.1` é +/-10%). Use `{ vary: 0.1 }` em tudo que dispara repetidamente. Não faz nada para um nome não definido.')],
            [t('`audio.tone`', '`audio.tone`'), t('`tone({ frequency = 440, type = \'square\', duration = 0.15, gain = 0.3, slide = 0, attack = 0.005, delay = 0, destination })`', '`tone({ frequency = 440, type = \'square\', duration = 0.15, gain = 0.3, slide = 0, attack = 0.005, delay = 0, destination })`'), t('One note. `slide` is Hz added to the pitch by the end (an exponential bend): the difference between a beep and a jump, a laser or a power-up. Returns the oscillator, or `undefined` when muted.', 'Uma nota. `slide` é o quanto de Hz se soma ao tom até o fim (uma curva exponencial): a diferença entre um bipe e um pulo, um laser ou um power-up. Devolve o oscilador, ou `undefined` quando mudo.')],
            [t('`audio.noise`', '`audio.noise`'), t('`noise({ duration = 0.3, gain = 0.3, frequency = 1200, type = \'lowpass\', sweep = 0, Q = 1, delay = 0 })`', '`noise({ duration = 0.3, gain = 0.3, frequency = 1200, type = \'lowpass\', sweep = 0, Q = 1, delay = 0 })`'), t('Filtered white noise: explosions, footsteps, wind, hits. `sweep` is Hz added to the filter cutoff by the end.', 'Ruído branco filtrado: explosões, passos, vento, impactos. `sweep` é o quanto de Hz se soma ao corte do filtro até o fim.')],
            [t('`audio.define`', '`audio.define`'), t('`define(name, factory)`', '`define(name, factory)`'), t('Registers your own sound, callable by name like the built-ins. The factory receives the `play` options and schedules `tone` and `noise` calls.', 'Registra um som seu, chamável por nome como os embutidos. A factory recebe as opções do `play` e agenda chamadas de `tone` e `noise`.')],
            [t('`audio.sounds`', '`audio.sounds`'), t('`Record<string, SoundFactory>`', '`Record<string, SoundFactory>`'), t('The named sounds.', 'Os sons nomeados.')],
          ],
        },
        {
          type: 'p',
          text: t(
            'Built-in sounds for `play`: `click`, `blip`, `select`, `coin`, `jump`, `land`, `hit`, `hurt`, `laser`, `shoot`, `explosion`, `powerup`, `win`, `lose`, `step`, `whoosh`, `thud`, `alarm`. They are tuned to sit together: nothing is louder or brighter than the rest by accident.',
            'Sons embutidos para o `play`: `click`, `blip`, `select`, `coin`, `jump`, `land`, `hit`, `hurt`, `laser`, `shoot`, `explosion`, `powerup`, `win`, `lose`, `step`, `whoosh`, `thud`, `alarm`. Eles são afinados para combinar: nada é mais alto ou mais brilhante que o resto por acidente.',
          ),
        },
      ],
    },
    {
      id: 'control',
      title: t('Music, volume and lifecycle', 'Música, volume e ciclo de vida'),
      blocks: [
        {
          type: 'props',
          rows: [
            { name: 'audio.music.start', type: '({ notes, tempo = 240, type = \'triangle\', gain = 0.08 })', description: t('A looping arpeggio bed. Default notes `[220, 277, 330, 440, 330, 277]` are an A major arpeggio; `tempo` is notes per minute. Not a soundtrack.', 'Uma trilha de arpejo em loop. As notas padrão `[220, 277, 330, 440, 330, 277]` formam um arpejo de lá maior; `tempo` é notas por minuto. Não é uma trilha sonora.') },
            { name: 'audio.music.stop', type: '() => void', description: t('Stops the music.', 'Para a música.') },
            { name: 'audio.volume', type: 'number', description: t('Master volume (get and set).', 'Volume mestre (leitura e escrita).') },
            { name: 'audio.mute / audio.toggleMute', type: '(value = true) / ()', description: t('Both return the audio object. `audio.muted` is the flag: set it through `mute`, since writing the field alone does not touch the master gain.', 'Ambos devolvem o objeto de áudio. `audio.muted` é a flag: altere por `mute`, pois escrever só no campo não mexe no ganho mestre.') },
            { name: 'audio.ready', type: 'boolean', readonly: true, description: t('True once the browser has let audio start. It is a boolean, not a Promise.', 'Verdadeiro quando o navegador liberou o áudio. É um boolean, não uma Promise.') },
            { name: 'audio.unlock', type: '() => void', description: t('Starts the context now (call it from a gesture handler if you need to).', 'Inicia o contexto agora (chame de um handler de gesto se precisar).') },
            { name: 'audio.dispose', type: '() => void', description: t('Stops the music, closes the audio context and removes the window listeners.', 'Para a música, fecha o contexto de áudio e remove os listeners da janela.') },
          ],
        },
        {
          type: 'callout',
          kind: 'warning',
          title: t('Edge cases', 'Casos de borda'),
          text: t(
            '`play(\'toString\')` and other names found on `Object.prototype` hit the prototype, because `sounds` is a plain object. `dispose` is not a hard stop for direct `tone()` calls: a later `tone()` builds a new audio context.',
            '`play(\'toString\')` e outros nomes presentes em `Object.prototype` acertam o protótipo, porque `sounds` é um objeto simples. `dispose` não é uma parada definitiva para chamadas diretas de `tone()`: um `tone()` posterior cria um novo contexto de áudio.',
          ),
        },
      ],
    },
  ],
}

export default page
