import { t, type DocPage } from '../../types'

const page: DocPage = {
  slug: '/guide/2d-or-3d',
  title: t('2D or 3D?', '2D ou 3D?'),
  description: t(
    'How the two engines differ, what each one is good at and how the choice is recorded in your project.',
    'Como as duas engines diferem, no que cada uma é boa e como a escolha fica registrada no seu projeto.',
  ),
  source: 'src/engine/config.ts',
  related: ['/introduction', '/guide/concepts', '/first-game', '/3d/quickstart', '/cli/new'],
  sections: [
    {
      id: 'two-engines',
      title: t('Two engines, one package', 'Duas engines, um pacote'),
      blocks: [
        {
          type: 'p',
          text: t(
            'The 2D engine is imported from `easy-game-maker` and draws with its own WebGL2 renderer. The 3D engine is imported from `easy-game-maker/3d` and is built on three.js, which the project installs as a dependency (`three` 0.185.x). They are separate. The 2D `App` has no 3D mode, and a 3D game does not use scenes or display objects from the 2D engine.',
            'A engine 2D é importada de `easy-game-maker` e desenha com o próprio renderizador WebGL2. A engine 3D é importada de `easy-game-maker/3d` e é construída sobre o three.js, que o projeto instala como dependência (`three` 0.185.x). Elas são separadas. O `App` 2D não tem modo 3D, e um jogo 3D não usa as cenas nem os objetos de exibição da engine 2D.',
          ),
        },
        {
          type: 'p',
          text: t(
            'You pick one per project, when you run `egm new`. There is no converter between them.',
            'Você escolhe uma por projeto, ao rodar `egm new`. Não existe conversor entre elas.',
          ),
        },
      ],
    },
    {
      id: 'comparison',
      title: t('Side by side', 'Lado a lado'),
      blocks: [
        {
          type: 'table',
          head: [t('Topic', 'Assunto'), t('2D', '2D'), t('3D', '3D')],
          rows: [
            [t('Entry', 'Entrada'), t('`new App(...)`, scenes, `app.run()`', '`new App(...)`, cenas, `app.run()`'), t('`createGame(...)`, loop already running', '`createGame(...)`, laço já em execução')],
            [t('Rendering', 'Renderização'), t('Own WebGL2 batcher', 'Batcher WebGL2 próprio'), t('three.js', 'three.js')],
            [t('Physics', 'Física'), t('Rigid bodies with planck.js (Box2D port)', 'Corpos rígidos com planck.js (port do Box2D)'), t('Arcade collision: floors, walls, triggers. Nothing tumbles or stacks', 'Colisão arcade: chão, paredes e gatilhos. Nada tomba nem empilha')],
            [t('Art', 'Arte'), t('Sprites, sprite sheets, Tiled tilemaps, shaders', 'Sprites, sprite sheets, tilemaps do Tiled e shaders'), t('No art shipped: models are built from primitives, textures are drawn in code, sound is synthesised. `.glb` files can be loaded', 'Sem arte incluída: modelos vêm de primitivas, texturas são desenhadas em código e o som é sintetizado. Arquivos `.glb` podem ser carregados')],
            [t('Interface', 'Interface'), t('`Text` and shapes on the canvas', '`Text` e formas no canvas'), t('HUD in the DOM over the canvas', 'HUD no DOM sobre o canvas')],
            [t('Visual Editor', 'Editor Visual'), t('Yes (`egm new --visual`)', 'Sim (`egm new --visual`)'), t('Not for scenes; `egm editor` opens a code editor in 3D mode', 'Não para cenas; o `egm editor` abre um editor de código no modo 3D')],
            [t('Multiplayer', 'Multiplayer'), t('`NetworkManager` over WebSocket', '`NetworkManager` sobre WebSocket'), t('Not part of `easy-game-maker/3d`', 'Não faz parte do `easy-game-maker/3d`')],
            [t('Generated by chat', 'Gerado por chat'), t('No', 'Não'), t('Yes, through [EGM AI](/guide/ai)', 'Sim, pelo [EGM AI](/guide/ai)')],
          ],
        },
      ],
    },
    {
      id: 'choosing',
      title: t('How to choose', 'Como escolher'),
      blocks: [
        {
          type: 'list',
          items: [
            t('Pick **2D** for puzzle, card, board, arcade, platformer and anything that is drawn from sprites or grids.', 'Escolha **2D** para quebra-cabeça, cartas, tabuleiro, arcade, plataforma e tudo o que é desenhado com sprites ou grades.'),
            t('Pick **3D** when depth, a moving camera or lighting is part of the game, or when you have no art and want a game that looks finished from primitives.', 'Escolha **3D** quando profundidade, câmera móvel ou iluminação fazem parte do jogo, ou quando você não tem arte e quer um jogo que pareça pronto usando primitivas.'),
            t('If you want rigid-body physics with stacking and rolling, that is the 2D engine today.', 'Se você quer física de corpos rígidos com empilhamento e rolagem, hoje isso é a engine 2D.'),
            t('Both run in the simulator and both package as a desktop app.', 'As duas rodam no simulador e as duas empacotam como aplicativo desktop.'),
          ],
        },
      ],
    },
    {
      id: 'recorded-in-config',
      title: t('How the choice is recorded', 'Como a escolha fica registrada'),
      blocks: [
        {
          type: 'p',
          text: t(
            '`egm new --3d` writes `mode: "3d"` into `egm.config.ts`. Without it, `mode` defaults to `"2d"`. The simulator and the editor read that value to configure themselves, so keep it as a plain string literal.',
            '`egm new --3d` escreve `mode: "3d"` no `egm.config.ts`. Sem ele, `mode` assume `"2d"`. O simulador e o editor leem esse valor para se configurar, então mantenha-o como um literal de texto simples.',
          ),
        },
        {
          type: 'code',
          lang: 'ts',
          filename: 'egm.config.ts',
          code: `import { defineConfig } from 'easy-game-maker'

export default defineConfig({
  app: { name: 'Sky Run', version: '1.0.0', bundleId: 'com.example.skyrun' },
  mode: '3d',
  display: {
    width: 1280,
    height: 720,
    orientation: 'landscape',
    backgroundColor: '#101827',
  },
})`,
        },
      ],
    },
  ],
}

export default page
